### PR TITLE
Return access and refresh tokens with `RetrieveTokenError`

### LINKED ISSUE #167: Improving the ergonomics of fallible `UserToken::from_existing_or_refresh_token`
The method `UserToken::from_existing_or_refresh_token` taking ownership of `RefreshToken` and `AccessToken` when refreshing the token makes sense logically on success as you won't need to reuse the tokens afterwards. 

But since it's fallible it means that on error both tokens are just lost, since the function doesn't give them back. 

This means that the Twitch server can just randomly respond with a 500 response and you don't have a choice but to either start over the entire auth flow or just crash. 

Searching usages of the function on GitHub, the only 2 usages both `.clone()` the tokens to use the function, completely invalidating any semantic meaning in taking ownership of the tokens. 

https://github.com/Emilgardis/twitch_discord_moderation/blob/cfc65f165f075f73f6184f2dad8a882483bcd010/src/subscriber.rs#L78-L85
https://github.com/L00Cyph3r/operation-warbot/blob/6127e08d96efcdfe3171ba7089619c42d11d0752/src/bot/auth.rs#L238-L245

The solutions to this could be the function taking mutable references to the tokens instead of ownership or returning the tokens on error. 
The former may lead to previously unreachable state of tokens, the latter may be more semantically correct but looks less clean in code

### PR DESCRIPTION
**Pull request by sby1ce**
Pull request for #167 

Changes signatures of several functions to include access and refresh tokens to include them in `RetrieveTokenError` and moves variants to `RetrieveTokenErrorKind`.

### CODE REVIEW

File: src/tokens/user_token.rs [hunk 1]
```diff
@@ -73,18 +73,40 @@ impl UserToken {
...
         validated: ValidatedToken,
         client_secret: impl Into<Option<ClientSecret>>,
-    ) -> Result<UserToken, ValidationError<std::convert::Infallible>> {
+    ) -> Result<
+        UserToken,
+        (
+            AccessToken,
+            Option<RefreshToken>,
+            ValidationError<std::convert::Infallible>,
+        ),
```
Comment (Emilgardis) [inline src/tokens/user_token.rs:82]: it seems to me that `ValidationError` could contain the `AccessToken` and `Option<RefreshToken>` and that way we could skip changing the signature and make the function more ergonomic with `Err(From::from(e))` with `?`

File: src/tokens/errors.rs [hunk 2]
```diff
@@ -38,11 +41,46 @@ impl ValidationError<std::convert::Infallible> {
...
+        }
+    }
+}
+
+/// Error kinds for [UserToken::from_refresh_token][crate::UserToken::from_refresh_token] and [UserToken::UserToken::from_existing_or_refresh_token][crate::UserToken::from_existing_or_refresh_token]
 #[derive(thiserror::Error, Debug, displaydoc::Display)]
 #[non_exhaustive]
 #[cfg(feature = "client")]
-pub enum RetrieveTokenError<RE: std::error::Error + Send + Sync + 'static> {
+pub enum RetrieveTokenErrorKind<RE: std::error::Error + Send + Sync + 'static> {
```
Comment (Emilgardis) [inline src/tokens/errors.rs:83]: I'm not a huge fan of this pattern, I think it is confusing, the kinds can contain the fields instead, e.g 

```rs
pub enum RetrieveTokenErrorKind<RE: std::error::Error + Send + Sync + 'static> {
    /// could not validate token
    // I think this wouldn't be needed though if ValidationError already contains the data, see other comment
    ValidationError(#[source] ValidationError<RE>, AccessToken, Option<RefreshToken>),
    /// could not refresh token
    RefreshTokenError(#[source] RefreshTokenError<RE>, AccessToken, Option<RefreshToken>),
}
```

**Review by Emilgardis — CHANGES_REQUESTED** [review]
Thank you for the PR! some suggestions!

File: src/tokens/user_token.rs (hunk 1 above)
Comment (sby1ce) [reply src/tokens/user_token.rs]: Made a `CreationError` struct to wrap the `ValidationError` and slapped a bunch of `From` impls everywhere, seems to be working

**Review by Emilgardis — CHANGES_REQUESTED** [review]
Awesome! Some minor changes and then I think we can merge this!

**Comment by sby1ce** [comment]
> Awesome! Some minor changes and then I think we can merge this!

Thanks for taking your time to review this bs PR 😂

**Review by Emilgardis — APPROVED** [review]
Thank you!!

**Comment by Emilgardis** [comment]
Audit failed, should just need a `cargo update -p tokio`

**Comment by Emilgardis** [comment]
deny.toml needs to be updated to include `RUSTSEC-2025-0036`
